### ISSUE TITLE
add distrubute point and build

### ISSUE THREAD

**Issue by mhf-ir** [ffissore/geoip-rs#1]
Thanks so much for awesome project.

How about using https://packagecloud.io/ or any service for dist as OS package.

How non-Rust developer using this package for usage.

**Comment by ffissore** [comment]
Hi @mhf-ir, I have
* slightly improved the installation instructions on the readme (= you don't need to be a rust dev to build it, just as you don't need to be a ruby dev to use a command line tool written in ruby)
* added pre-built binary to each release, starting from 0.5.1 https://github.com/ffissore/geoip-rs/releases/tag/0.5.1

Hope this helps: let me know what you think
