### ISSUE TITLE
Question about use of https://geoip.rs

### ISSUE THREAD

**Issue by silvioprog** [ffissore/geoip-rs#3]
Hi.

I'm developing a small open source tool for retrieving weather info that retrieves the latitude/longitude from the user location. Since your service provides exactly this, I would like to use it to fix [this issue](https://github.com/risoflora/wethr/issues/4), however I can't measure how many people will use the tool.

Can I use your service for this purpose?

TIA for any help!

**Comment by ffissore** [comment]
You are welcome to use geoio.rs. However, bear in mind that its website is meant for demoing the tool rather than providing precise data (ie: data could be stale).
If you need up-to-date data, you want to look for services that have a business behind them: just google "geoip"
